name: Example Workflow
on: push
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run summary
        run: |
          export GITHUB_STEP_SUMMARY=$GITHUB_STEP_SUMMARY
          ./entrypoint.sh --chunks 42
