name: Recreate Production Markdown Issue

on:
  workflow_dispatch:

jobs:
  test-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "INPUT_IMAGE=python:3.12-slim" >> $GITHUB_ENV
          echo "INPUT_COMMAND=python3 -m lectoncli.write_summary --chunks 42" >> $GITHUB_ENV

      - name: Run entrypoint
        run: ./entrypoint.sh
        shell: bash
